spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?useSSL=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true